# fly.toml app configuration file generated for library-scanner on 2026-08-18T20:38:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'library-scanner'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  DATABASE_URL = "file:/data/sqlite.db"

[mounts]
  source = "sqlite_data"
  destination = "/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
